# Generated by Django 4.2.2 on 2024-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
    ]
